spring.application.name=pos
application.version=1.0.0

server.port=8080

#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/posdb}
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://posdb.cckrkpzdxqoo.ap-south-1.rds.amazonaws.com:5432/financedb
spring.datasource.username=postgres
spring.datasource.password=EEdMgK9Lr4Zcp3X
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update